name: Deploy Next.js application

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4

            - name: Create .env file
              run: |
                  echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
                  echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
                  echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
                  echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
                  echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
                  echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
                  echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
                  echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env
                  echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> .env
                  echo "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" >> .env
                  echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> .env
                  echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
                  echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" >> .env
                  echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" >> .env
                  echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env
                  echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env

            - name: Build Docker image
              run: docker build -t prominhaj/learn-pulse-edu .

            - name: Login to Docker Hub
              run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: Publish image to Docker Hub
              run: docker push prominhaj/learn-pulse-edu:latest

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Check Disk Space
              run: df -h

            - name: Free up Docker space
              run: |
                  docker system prune -af
                  docker volume prune -f

            - name: Pull image from Docker Hub
              run: docker pull prominhaj/learn-pulse-edu:latest

            - name: Prune unused Docker data
              run: docker system prune -f

            - name: Stop and remove old container if exists
              run: |
                  if [ $(docker ps -q -f name=learn-pulse-edu-container) ]; then
                    docker stop learn-pulse-edu-container
                    docker rm learn-pulse-edu-container
                  fi

            - name: Run Docker container
              run: docker run -d -p 3000:3000 --env-file .env --name learn-pulse-edu-container prominhaj/learn-pulse-edu:latest
